# Generated by Django 4.1.7 on 2023-03-22 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='phone_no',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
