# Generated by Django 4.1.7 on 2023-03-23 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_profile_phone_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='end_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='events',
            name='start_date',
            field=models.DateTimeField(null=True),
        ),
    ]
