# Generated by Django 4.1.7 on 2023-03-23 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_events_end_date_alter_events_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='completed',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='events',
            name='paid',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='packages',
            name='date_added',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='packages',
            name='duration',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='packages',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='packages',
            name='price',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='', null=True, upload_to='image/users_img'),
        ),
    ]
