# Generated by Django 4.1.7 on 2023-03-24 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_events_completed_events_paid_packages_date_added_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='events',
            old_name='end_date',
            new_name='end_date_time',
        ),
        migrations.RenameField(
            model_name='events',
            old_name='start_date',
            new_name='start_date_time',
        ),
        migrations.AddField(
            model_name='events',
            name='duration',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
