# Generated by Django 4.1.7 on 2023-03-24 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_rename_end_date_events_end_date_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='events',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
