# Generated by Django 4.1.7 on 2023-03-24 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_events_completed_alter_events_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='duration',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
