# Generated by Django 4.1.7 on 2023-03-24 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_events_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='duration',
            field=models.IntegerField(blank=True, default='', null=True),
        ),
    ]
