# Generated by Django 4.1.7 on 2023-03-24 21:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0009_alter_events_duration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='events',
            old_name='completed',
            new_name='passed',
        ),
        migrations.AddField(
            model_name='cartedevent',
            name='events',
            field=models.ManyToManyField(blank=True, related_name='carted_event', to='main.events'),
        ),
        migrations.AddField(
            model_name='cartedevent',
            name='otp_code',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='cartedevent',
            name='packages',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='main.packages'),
        ),
        migrations.AddField(
            model_name='cartedevent',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cartedevent',
            name='txref_id',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='cartedevent',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payedevents',
            name='carted_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.cartedevent'),
        ),
        migrations.AddField(
            model_name='payedevents',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='payedevents',
            name='txref_id',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='duration',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
