# Generated by Django 4.1.7 on 2023-03-26 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_events_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='ads_end_date_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='events',
            name='ads_start_date_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
