# Generated by Django 4.1.7 on 2023-03-29 23:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0012_events_ads_end_date_time_events_ads_start_date_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartedevent',
            name='otp_code',
        ),
        migrations.AddField(
            model_name='payedevents',
            name='otp_code',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='payedevents',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
