# Generated by Django 4.1.7 on 2023-03-31 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_remove_packages_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartedevent',
            name='total',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
