# Generated by Django 4.1.7 on 2023-03-31 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_cartedevent_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartedevent',
            name='total',
        ),
    ]
